# Generated by Django 5.2 on 2025-05-20 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_empresa_activo_perfilusuario_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.activo'),
        ),
    ]
