# Generated by Django 5.2 on 2025-05-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ticket_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('tecnico', 'Técnico'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comentario_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
