services:
  - type: web
    name: asset-management
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd reto-cuc-main/asset_management && gunicorn asset_management.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: asset-management-db
          property: connectionString

databases:
  - name: asset-management-db
    databaseName: asset_management
    user: asset_user
